name: Build and Push Docker image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Gitea
        run: echo "${{ secrets.PASSWORD }}" | docker login -u ${{ secrets.USERNAME }} --password-stdin git.nejer6.ru

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build
        run: ./gradlew build

      - name: Build the Docker image
        run: docker build -t git.nejer6.ru/nejer/random-file:${{ gitea.ref_name }} .

      - name: Push the Docker image
        run: docker push git.nejer6.ru/nejer/random-file:${{ gitea.ref_name }}
